networks:
  kovan:
    weth_token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
  mainnet-fork-dev: # i've set up this instead of mainnet-fork in brwonie networks list
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
wallets:
  from_key: ${PRIVATE_KEY}
